ChildrenCare/Controllers/AdminController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ChildrenCare.Controllers
{
    public class AdminController : Controller
    {
        // GET: AdminController
        public ActionResult AdminDashboard()
        {
            return View();
        }

        // GET: AdminController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AdminController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }

        // GET: AdminController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: AdminController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }

        // GET: AdminController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AdminController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }
    }
}

ChildrenCare/Controllers/AppUserController.cs
using ChildrenCare.DTOs.AppUserDTOs;
using ChildrenCare.Services.Interface;
using ChildrenCare.Utilities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ChildrenCare.Controllers
{
    public class AppUserController : Controller
    {
        private readonly IAppUserService _appUserService;

        // public IActionResult Index()
        // {
        //     return View();
        // }

        public AppUserController(IAppUserService appUserService)
        {
            _appUserService = appUserService;
        }

        [HttpGet]
        public IActionResult Register()
        {
            //Lấy list các gender
            RegisterRequestDTO dto = new RegisterRequestDTO();
            IEnumerable<GlobalVariables.GenderType> genderTypes =
                Enum.GetValues(typeof(GlobalVariables.GenderType)).Cast<GlobalVariables.GenderType>();
            dto.GenderList = from genderType in genderTypes
                select new SelectListItem() { Text = genderType.ToString(), Value = ((int)genderType).ToString() };
            return View(dto);
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterRequestDTO dto)
        {
            //Trim tất cả các string trong object
            dto = (RegisterRequestDTO)ObjectTrimmer.TrimObject(dto);

            var result = await _appUserService.Register(dto);
            if (!result.IsSuccess)
            {
                ModelState.AddModelError(string.Empty, result.Message);
                IEnumerable<GlobalVariables.GenderType> genderTypes =
                    Enum.GetValues(typeof(GlobalVariables.GenderType)).Cast<GlobalVariables.GenderType>();
                dto.GenderList = from genderType in genderTypes
                    select new SelectListItem() { Text = genderType.ToString(), Value = ((int)genderType).ToString() };
                return View("Register", dto);
            }

            return RedirectToAction("Login");
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View("Login");
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await _appUserService.Logout();
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginRequestDTO dto)
        {
            dto = (LoginRequestDTO)ObjectTrimmer.TrimObject(dto);

            if (!ModelState.IsValid)
            {
                return View("Login");
            }

            var result = await _appUserService.Login(dto);

            if (!result.IsSuccess)
            {
                ViewBag.ErrorMessage = result.Message;
                return View("Login");
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

ChildrenCare/Controllers/SliderController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ChildrenCare.Data;
using ChildrenCare.Entities;
using ChildrenCare.Services;
using ChildrenCare.Services.Interface;

namespace ChildrenCare.Controllers
{
    public class SliderController : Controller
    {
        private readonly ChildrenCareDBContext dBContext;
        private readonly ISliderService _sliderService;

        public SliderController(ChildrenCareDBContext dBContext, ISliderService sliderService)
        {
            this.dBContext = dBContext;
            _sliderService = sliderService;
        }

        // GET: SliderController
        public ActionResult SliderList()
        {   
            var list = dBContext.Sliders.ToList();
            return View(list);
        }

        [HttpGet]
        public async Task<IActionResult> SearchSliderList(string status, string title, string backlink)
        {
            ViewData["CurrentStatus"] = status;
            ViewData["CurrentTitle"] = title;
            ViewData["CurrentBacklink"] = backlink;
            if (string.IsNullOrEmpty(status))
                status = "";
            if (string.IsNullOrEmpty(title))
                title = "";
            if (string.IsNullOrEmpty(backlink))
                backlink = "";
            var list = await _sliderService.SearchSlider(status, title, backlink);
            return View("SliderList", list);
        }

        // GET: SliderController/Details/5
        public ActionResult SliderDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var detail = dBContext.Sliders.FirstOrDefault(s => s.Id == id);
            if (detail == null)
            {
                return NotFound();
            }
            return View(detail);
        }

        // GET: SliderController/Create
        public ActionResult CreateSlider()
        {
            return View();
        }

        // POST: SliderController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateSlider(Slider slider)
        {
            if (ModelState.IsValid)
            {
                dBContext.Add(slider);
                dBContext.SaveChanges();
                return RedirectToAction(nameof(SliderList));
            }
            return View(slider);
        }

        // GET: SliderController/Edit/5
        public ActionResult UpdateSlider(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var detail = dBContext.Sliders.Find(id);
            if (detail == null)
            {
                return NotFound();
            }
            return View(detail); 
        }

        // POST: SliderController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateSlider(int id, Slider slider)
        {
            if (id != slider.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                dBContext.Update(slider);
                dBContext.SaveChanges();
                TempData["Success"] = "Update Succesfully";
                return RedirectToAction(nameof(UpdateSlider));
            }
            return View(slider);
        }

        // GET: SliderController/Delete/5
        public ActionResult DeleteSlider(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var slider = dBContext.Sliders.Find(id);
            if (slider == null)
            {
                return NotFound();
            }
            return View(slider);
            //var slider = dBContext.Sliders.Find(id);
            //dBContext.Sliders.Remove(slider);
            //dBContext.SaveChanges();
            //return RedirectToAction(nameof(CreateSlider));
        }

        // POST: SliderController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteSlider(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var slider = dBContext.Sliders.Find(id);
            if (ModelState.IsValid)
            {               
                dBContext.Sliders.Remove(slider);
                dBContext.SaveChanges();
                return RedirectToAction(nameof(SliderList));
            }
            return View(slider);
        }

    }
}

ChildrenCare/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using ChildrenCare.Entities
@using ChildrenCare.Utilities
@using System.Security.Claims

@inject SignInManager<AppUser> SignInManager
@inject RoleManager<AppRole> RoleManager
@inject UserManager<AppUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChildrenCare</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link rel="stylesheet" href="~/css/homepage.css" type="text/css">
    <link rel="icon" href="~/images/logo.svg" type="image/svg+xml">
</head>
<body>

    <nav class="navbar navbar-expand-lg bg-white">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/logo.svg" style="height: 50px; width: 50px;"/> ChildrenCare</a>
            <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarnav">
                <i class="navbar-icon fa-solid fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse justify-content-center" id="navbarnav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Service" asp-action="ServiceList">Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Blog" asp-action="BlogList">Blogs</a>
                    </li>
                </ul>
            </div>
            <div class="navbar-action d-flex float-end">
                @if (SignInManager.IsSignedIn(User))
                {
                    <div class="dropdown dropdown-start">
                        <div class="user-avatar" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown"
                         aria-expanded="false">
                            <img src="~/images/user.png" alt="userimg" style="height: 50px; width: 50px">
                        </div>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                            <li><a class="dropdown-item" asp-controller="Home" asp-action="Profile" asp-route-id="@User.FindFirstValue(ClaimTypes.NameIdentifier)">My Profile</a></li>
                            @if (User.IsInRole(GlobalVariables.CustomerRole))
                            {
                                <li><a id="manage" class="dropdown-item" asp-controller="Reservation" asp-action="MyReservation">My Reservations</a></li>
                            }
                            @if (User.IsInRole(GlobalVariables.ManagerRole))
                            {
                                <li><a id="manage" class="dropdown-item" asp-controller="Blog" asp-action="BlogManagement">Manager Dashboard</a></li>
                            }
                            @if (User.IsInRole(GlobalVariables.DoctorRole) || User.IsInRole(GlobalVariables.NurseRole))
                            {
                                <li><a id="manage" class="dropdown-item" asp-controller="Reservation" asp-action="ReservationManagement">Staff Dashboard</a></li>
                            }
                            @if (User.IsInRole(GlobalVariables.AdministratorRole))
                            {
                                <li><a id="manage" class="dropdown-item" asp-controller="Customer" asp-action="CustomerList">Manage Customers</a></li>
                            }
                            <li><a id="manage" class="dropdown-item" asp-controller="AppUser" asp-action="Logout">Logout</a></li>
                        </ul>
                    </div>
                }
                else
                {
                    <div class="navbar-action d-flex float-end">
                        <a class="nav-link text-dark" id="register" asp-controller="AppUser" asp-action="Register">Register</a>
                        <a class="nav-link text-dark" id="login" asp-controller="AppUser" asp-action="Login">Login</a>
                    </div>
                }

            </div>
        </div>
    </nav>


    @RenderBody()


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - childrencare - <a asp-area="" asp-controller="home" asp-action="privacy">privacy</a>
        </div>
    </footer>
    @*@await RenderSectionAsync("Scripts", false)*@

</body>
</html>

ChildrenCare/Views/Shared/_LayoutAdmin.cshtml
@using Microsoft.AspNetCore.Identity
@using ChildrenCare.Entities
@using ChildrenCare.Utilities

@inject SignInManager<AppUser> SignInManager
@inject RoleManager<AppRole> RoleManager
@inject UserManager<AppUser> UserManager

<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.8.0/chart.min.js"
            integrity="sha512-sW/w8s4RWTdFFSduOTGtk4isV1+190E/GghVffMA9XczdJ2MDzSzLEubKAs5h0wzgSJOQTRYyaz73L3d6RtJSg=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <title>Admin | ChildrenCare</title>
    <link href="~/css/admin.css" rel="stylesheet" type="text/css">
    <script src="~/js/main.js" type="text/javascript"></script>
    <link rel="icon" href="~/images/logo.svg" type="image/svg+xml">
</head>

<body id="body-pd" class="body-pd">
    <header class="header body-pd" id="header">
        <div class="header_toggle">
            <i class='bx bx-menu bx-x' id="header-toggle"></i>
        </div>

        <div class="header_img">
            <img src="~/images/avatar4.png" alt="">
        </div>
    </header>
    <div class="l-navbar show" id="nav-bar">
        <nav class="nav">
            <div>
                <a class="nav_logo" asp-area="" asp-controller="Home" asp-action="Index">
                    <span class="nav_logo-name">
                        <i class='bx bx-plus-medical nav-icon'></i>
                        ChildrenCare
                    </span>
                </a>
                <div class="nav_list">
                    
                        @* <a asp-controller="Admin" asp-action="AdminDashboard" class="nav_link"> *@
                        @*     <i class='bx bxs-dashboard nav_icon'></i><span class="nav_name">Dashboard</span> *@
                        @* </a> *@
                        <a asp-controller="Customer" asp-action="CustomerList" class="nav_link">
                            <i class='bx bx-user-circle nav_icon'></i><span class="nav_name">Customers</span>
                        </a>
                </div>
            </div>
            <a asp-controller="AppUser" asp-action="Logout" class="nav_link">
                <i class='bx bx-log-out nav_icon'></i> <span class="nav_name">SignOut</span>
            </a>
        </nav>
    </div>

    @RenderBody()
    @await RenderSectionAsync("Scripts", false)
</body>
</html>

ChildrenCare/Views/Shared/_LayoutError.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Eror!</title>
    <link rel="icon" href="~/images/logo.svg" type="image/svg+xml">
</head>
<body>
    <div>
        <img src="~/images/block.jpg" alt="block" style="height: 100vh; width: 100vw"/>
    </div>
    <div hidden>
        @RenderBody()
    </div>
</body>
</html>

ChildrenCare/Views/Shared/_LayoutManager.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    <title>Manager | Medic</title>
    <link href="~/css/manager.css" rel="stylesheet" type="text/css">
    <script src="~/js/main.js" type="text/javascript"></script>
    <link rel="icon" href="~/images/logo.svg" type="image/svg+xml">
</head>

<body id="body-pd" class="body-pd">
<header class="header body-pd" id="header">
    <div class="header_toggle">
        <i class='bx bx-menu bx-x' id="header-toggle"></i>
    </div>

    <div class="header_img">
        <img src="./images/avatar4.png" alt="">
    </div>
</header>
<div class="l-navbar show" id="nav-bar">
    <nav class="nav">
        <div>
            <a class="nav_logo" asp-area="" asp-controller="Home" asp-action="Index">
                <span class="nav_logo-name">
                    <i class='bx bx-plus-medical nav-icon'></i>
                    ChildrenCare
                </span>
            </a>
            <div class="nav_list">
                @*<a href="#" class="nav_link">
                    <i class='bx bxs-dashboard nav_icon'></i><span class="nav_name">Dashboard</span>
                    </a>
                    <a href="#" class="nav_link">
                    <i class='bx bxs-cart-alt nav_icon'></i><span class="nav_name">Reservations</span>
                    </a>*@
                <a class="nav_link" asp-controller="Blog" asp-action="BlogManagement">
                    <i class='bx bx-list-plus nav_icon'></i><span class="nav_name">Blogs</span>
                </a>
                <a asp-controller="Slider" asp-action="SliderList" class="nav_link">
                    <i class='bx bx-slideshow nav_icon'></i><span class="nav_name">Sliders</span>
                </a>
                <a asp-controller="Service" asp-action="ServiceManagement" class="nav_link">
                    <i class='bx bx-task nav_icon'></i><span class="nav_name">Services</span>
                </a>
                <a asp-controller="Customer" asp-action="CustomerList" class="nav_link">
                    <i class='bx bx-user-circle nav_icon'></i><span class="nav_name">Customers</span>
                </a>
                <a asp-controller="StaffSpecialization" asp-action="Index" class="nav_link">
                    <i class='bx bxs-user-detail'></i><span class="nav_name">Staff Specialization</span>
                </a>
            </div>
        </div>
        <a asp-controller="AppUser" asp-action="Logout" class="nav_link">
            <i class='bx bx-log-out nav_icon'></i> <span class="nav_name">SignOut</span>
        </a>
    </nav>
</div>

@RenderBody()
@await RenderSectionAsync("Scripts", false)
</body>
</html>

ChildrenCare/Views/Shared/_LayoutRegister.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - ChildrenCare</title>
    <link rel="stylesheet" href="~/css/register.css">
    <link rel="icon" href="~/images/logo.svg" type="image/svg+xml">
</head>
<body>
    <div class="container">
        <div class="signup">
            @RenderBody()
        </div>
    </div>
</body>
</html>

ChildrenCare/Views/Shared/_LayoutStaff.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.8.0/chart.min.js"
            integrity="sha512-sW/w8s4RWTdFFSduOTGtk4isV1+190E/GghVffMA9XczdJ2MDzSzLEubKAs5h0wzgSJOQTRYyaz73L3d6RtJSg=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <title>Staff | ChildrenCare</title>
    <link href="~/css/manager.css" rel="stylesheet" type="text/css">
    <script src="~/js/main.js" type="text/javascript"></script>
    <link rel="icon" href="~/images/logo.svg" type="image/svg+xml">
</head>

<body id="body-pd" class="body-pd">
    <header class="header body-pd" id="header">
        <div class="header_toggle"><i class='bx bx-menu bx-x' id="header-toggle"></i></div>

        <div class="header_img">
            <img src="~/images/avatar4.png" alt="">
        </div>
    </header>
    <div class="l-navbar show" id="nav-bar">
        <nav class="nav">
            <div>
                <a class="nav_logo" asp-area="" asp-controller="Home" asp-action="Index">
                    <span class="nav_logo-name">
                        <i class='bx bx-plus-medical nav-icon'></i>
                        ChildrenCare
                    </span>
                </a>
                <div class="nav_list">
                    @*<a asp-controller="Admin" asp-action="AdminDashboard" class="nav_link">
                        <i class='bx bxs-dashboard nav_icon'></i><span class="nav_name">Dashboard</span>
                        </a>*@
                    <a asp-controller="Reservation" asp-action="ReservationManagement" class="nav_link">
                        <i class='bx bxs-cart-alt nav_icon'></i><span class="nav_name">Reservations</span>
                    </a>
                    <a asp-controller="Prescription" asp-action="PrescriptionsList" class="nav_link">
                        <i class='bx bxs-book-content nav_icon'></i><span class="nav_name">Prescription</span>
                    </a>


                    @*<a class="nav_link" asp-controller="Blog" asp-action="BlogManagement">
                        <i class='bx bx-list-plus nav_icon'></i><span class="nav_name">Blogs</span>
                        </a>
                        <a asp-controller="Slider" asp-action="SliderList" class="nav_link">
                        <i class='bx bx-slideshow nav_icon'></i><span class="nav_name">Sliders</span>
                        </a>
                        <a asp-controller="Service" asp-action="ServiceManagement" class="nav_link">
                        <i class='bx bx-task nav_icon'></i><span class="nav_name">Services</span>
                        </a>
                        <a class="nav_link">
                        <i class='bx bx-user-circle nav_icon'></i><span class="nav_name">Customers</span>
                        </a>
                        <a asp-controller="Feedback" asp-action="Index"class="nav_link">
                        <i class='bx bx-star'></i><span class="nav_name">Feedback</span>
                        </a>*@
                </div>
            </div>
            <a asp-controller="AppUser" asp-action="Logout" class="nav_link">
                <i class='bx bx-log-out nav_icon'></i> <span class="nav_name">SignOut</span>
            </a>
        </nav>
    </div>

    @RenderBody()
    @await RenderSectionAsync("Scripts", false)
</body>
</html>