ChildrenCare/Controllers/AppUserController.cs
using ChildrenCare.DTOs.AppUserDTOs;
using ChildrenCare.Services.Interface;
using ChildrenCare.Utilities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ChildrenCare.Controllers
{
    public class AppUserController : Controller
    {
        private readonly IAppUserService _appUserService;

        // public IActionResult Index()
        // {
        //     return View();
        // }

        public AppUserController(IAppUserService appUserService)
        {
            _appUserService = appUserService;
        }

        [HttpGet]
        public IActionResult Register()
        {
            //Lấy list các gender
            RegisterRequestDTO dto = new RegisterRequestDTO();
            IEnumerable<GlobalVariables.GenderType> genderTypes =
                Enum.GetValues(typeof(GlobalVariables.GenderType)).Cast<GlobalVariables.GenderType>();
            dto.GenderList = from genderType in genderTypes
                select new SelectListItem() { Text = genderType.ToString(), Value = ((int)genderType).ToString() };
            return View(dto);
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterRequestDTO dto)
        {
            //Trim tất cả các string trong object
            dto = (RegisterRequestDTO)ObjectTrimmer.TrimObject(dto);

            var result = await _appUserService.Register(dto);
            if (!result.IsSuccess)
            {
                ModelState.AddModelError(string.Empty, result.Message);
                IEnumerable<GlobalVariables.GenderType> genderTypes =
                    Enum.GetValues(typeof(GlobalVariables.GenderType)).Cast<GlobalVariables.GenderType>();
                dto.GenderList = from genderType in genderTypes
                    select new SelectListItem() { Text = genderType.ToString(), Value = ((int)genderType).ToString() };
                return View("Register", dto);
            }

            return RedirectToAction("Login");
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View("Login");
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await _appUserService.Logout();
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginRequestDTO dto)
        {
            dto = (LoginRequestDTO)ObjectTrimmer.TrimObject(dto);

            if (!ModelState.IsValid)
            {
                return View("Login");
            }

            var result = await _appUserService.Login(dto);

            if (!result.IsSuccess)
            {
                ViewBag.ErrorMessage = result.Message;
                return View("Login");
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

ChildrenCare/Controllers/HomeController.cs
using ChildrenCare.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ChildrenCare.Services.Interface;
using ChildrenCare.Data;
using ChildrenCare.DTOs.BlogDTOs;
using ChildrenCare.Entities;
using Microsoft.AspNetCore.Identity;
using ChildrenCare.Repositories.Interfaces;

namespace ChildrenCare.Controllers
{
    public class HomeController : Controller
    {
        private readonly IServiceService _service;
        private readonly IBlogService _blogService;
        private readonly ILogger<HomeController> _logger;

        private readonly ChildrenCareDBContext _dBContext;
        private readonly IAppUserService _appUserService;
        private readonly UserManager<AppUser> _userManager;

        private readonly RoleManager<AppRole> _roleManager;
        private readonly IRepositoryWrapper _repositoryWrapper;

        public HomeController(ILogger<HomeController> logger, IServiceService service, 
            ChildrenCareDBContext dBContext, IAppUserService appUserService,
            UserManager<AppUser> userManager, IBlogService blogService, RoleManager<AppRole> roleManager, IRepositoryWrapper repositoryWrapper)
        {
            _logger = logger;
            _service = service;
            _dBContext = dBContext;
            _appUserService = appUserService;
            _userManager = userManager;
            _blogService = blogService;
        }

        public async Task<IActionResult> Index()
        {
            var slider = _dBContext.Sliders.ToList();
            ViewBag.Services = await _service.GetFeaturedServiceList();
            ViewBag.Blogs = await _blogService.GetBlogList(new GetBlogListRequestDTO());
            return View(slider);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        // GET: AdminController/Home/Profile/5
        public async Task<IActionResult> Profile()
        {
            var id = _userManager.GetUserId(this.User);
            var appUser = await _userManager.FindByIdAsync(id);
            if (appUser == null)
            {
                return NotFound();
            }
            return View(appUser);
        }

        // POST: AdminController/Home/Profile/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Profile(int? id, AppUser appUser)
        {
            if (id != appUser.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _dBContext.Update(appUser);
                _dBContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(appUser);
        }
        
        // POST: AdminController/Home/Profile/5/ChangePassword
        public async Task<IActionResult> ChangePassword()
        {
            return View("ChangePassword");
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SubmitChangePassword(string newPassword, string confirmPassword)
        {
            if (!newPassword.Equals(confirmPassword))
            {
                return View("ChangePassword");
            }
            var user  = this.User;
            var id = _userManager.GetUserId(User);
            var appUser = await _userManager.FindByIdAsync(id);

            var result = await _appUserService.UpdatePassword(appUser, newPassword);
            if (result.IsSuccess)
            {
                return View("Profile", appUser);
            }
            return View("ChangePassword");
        }


        /////////////////////////////////////////
        public async Task<IActionResult> EditCustomer(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = await _userManager.FindByIdAsync(id.ToString());
            var listRole = await _userManager.GetRolesAsync(user);
            var userRole = await _roleManager.FindByNameAsync(listRole.First());
            ICollection<AppUserRole> userRoles = new List<AppUserRole>();
            AppUserRole appUserRole = new AppUserRole()
            {
                User = user,
                Role = userRole
            };
            userRoles.Add(appUserRole);
            user.UserRoles = userRoles;
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: AdminController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditCustomerEdit(AppUser appUser, string? inputRole)
        {
            var id = appUser.Id.ToString();
            var baseUser = await _userManager.FindByIdAsync(id);
            if (baseUser != null)
            {
                baseUser.Email = appUser.Email;
                baseUser.NormalizedEmail = appUser.Email.ToUpper();
                baseUser.Gender = appUser.Gender;
                baseUser.FullName = appUser.FullName;
                baseUser.PhoneNumber = appUser.PhoneNumber;
                await _userManager.UpdateAsync(baseUser);
            }
            return RedirectToAction("Profile", "Home");
        }

    }
}

ChildrenCare/Controllers/ServiceController.cs
using System.Security.Claims;
using ChildrenCare.Data;
using ChildrenCare.DTOs.ServiceDTOs;
using ChildrenCare.Services.Interface;
using ChildrenCare.Utilities;
using Microsoft.AspNetCore.Mvc;
using ChildrenCare.Entities;

namespace ChildrenCare.Controllers
{
    public class ServiceController : Controller
    {
        private readonly IServiceService _service;
        private readonly ChildrenCareDBContext db;

        // public IActionResult Index()
        // {
        //     return View();
        // }

        public ServiceController(IServiceService service, ChildrenCareDBContext dBContext)
        {
            _service = service;
            db = dBContext;
        }

        [HttpGet]
        public async Task<IActionResult> ServiceList()
        {            
            var requestDto = new AdvancedGetServiceRequestDTO()
            {
                SortBy = "status_asc",
                PageSize = 100,
                PageNumber = 1,
            };
            ViewBag.ServiceList = await _service.AdvancedGetServiceList(requestDto);
            return View("ServiceList");
        }

        [HttpPost]
        public async Task<IActionResult> ServiceList(AdvancedGetServiceRequestDTO dto)
        {
            //Trim tất cả các chuỗi trong object
            dto = (AdvancedGetServiceRequestDTO) ObjectTrimmer.TrimObject(dto);
            return View("ServiceList");
        }

        [HttpGet]
        public async Task<IActionResult> SearchService(string title)
        {
            ViewData["CurrentTitle"] = title;
            if (string.IsNullOrEmpty(title))
                title = "";
            var requestDto = new AdvancedGetServiceRequestDTO()
            {
                SortBy = "createddate_desc",
                PageSize = 100,
                PageNumber = 1,
                Title = title
            };
            ViewBag.ServiceList = await _service.AdvancedGetServiceList(requestDto);
            return View("ServiceList");
        }

        [HttpGet]
        public async Task<IActionResult> AddService(int id)
        {
            var result = await _service.AddService(id);
            if (result.IsSuccess) return RedirectToAction("ServiceList");
            ModelState.AddModelError("",result.Message);
            var requestDto = new AdvancedGetServiceRequestDTO()
            {
                SortBy = "createddate_desc",
                PageSize = 5,
                PageNumber = 1,
            };
            ViewBag.ServiceList = await _service.AdvancedGetServiceList(requestDto);

            return View("ServiceList");
        }

        public ActionResult ServiceManagement()
        {
            var list = db.Services.ToList();
            return View(list);
        }

        [HttpGet]
        public async Task<IActionResult> SearchServiceList(string status, string title, string briefInfo)
        {
            ViewData["CurrentStatus"] = status;
            ViewData["CurrentTitle"] = title;
            ViewData["CurrentBriefinfo"] = briefInfo;
            if (string.IsNullOrEmpty(status))
                status = "";
            if (string.IsNullOrEmpty(title))
                title = "";
            if (string.IsNullOrEmpty(briefInfo))
                briefInfo = "";
            var list = await _service.SearchService(status, title, briefInfo);
            return View("ServiceManagement", list);
        }

        // GET: ServiceController/Details/5
        public ActionResult ServiceDetail(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var detail = db.Services.FirstOrDefault(s => s.Id == id);
            if (detail == null)
            {
                return NotFound();
            }
            return View(detail);
        }

        public ActionResult ServiceDetailCus(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var detail = db.Services.FirstOrDefault(s => s.Id == id);
            if (detail == null)
            {
                return NotFound();
            }
            return View(detail);
        }

        // GET: ServiceController/Create
        public ActionResult CreateService()
        {
            return View();
        }

        // POST: ServiceController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateService(Service service)
        {
            if (ModelState.IsValid)
            {
                db.Add(service);
                db.SaveChanges();
                return RedirectToAction(nameof(ServiceManagement));
            }
            return View(service);
        }

        // GET: ServiceController/Edit/5
        public ActionResult UpdateService(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var detail = db.Services.Find(id);
            if (detail == null)
            {
                return NotFound();
            }
            return View(detail);
        }

        // POST: ServiceController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateService(int id, Service service)
        {
            if (id != service.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                db.Update(service);
                db.SaveChanges();
                TempData["Success"] = "Update Succesfully";
                return RedirectToAction(nameof(UpdateService));
            }
            return View(service);
        }

        // GET: ServiceController/Delete/5
        public ActionResult DeleteService(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var service = db.Services.Find(id);
            if (service == null)
            {
                return NotFound();
            }
            return View(service);
        }

        // POST: ServiceController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteService(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var service = db.Services.Find(id);
            if (ModelState.IsValid)
            {
                db.Services.Remove(service);
                db.SaveChanges();
                return RedirectToAction(nameof(ServiceManagement));
            }
            return View(service);
        }
    }
}

ChildrenCare/Views/Home/ChangePassword.cshtml
@using ChildrenCare.Utilities
@model ChildrenCare.Entities.AppUser

@{
    ViewData["Title"] = "Profile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section id="user-profile">
    <div class="container mb-5">
        <div class="nav-sub">
            <nav class="nav">
                <a class="nav-link" asp-controller="Home" asp-action="Profile">Your Information</a>
                <a class="nav-link" asp-action="ChangePassword">Change Password</a>
            </nav>
        </div>
        <h3 class="fw-bold mt-3">Account Information</h3>
        <div class="user-profile-wrapper mt-3">
            <div class="row p-5">
                @*<div class="user-role col-4 d-flex flex-column justify-content-center align-items-center">*@
                    @*<div class="user-img-border d-flex justify-content-center align-items-center mb-1">
                        <div class="user-img bg-info d-flex justify-content-center">
                            <img class="rounded" src="./images/doctor.png" alt=".">
                        </div>
                        <label for="image-upload"
                               class="icon-camera d-flex justify-content-center align-items-center">
                            <i class="fa fa-camera text-white"></i>
                            <input type="file" id="image-upload" accept="image/x-png,image/gif,image/jpeg">
                        </label>
                    </div>*@
                    @*<div class="user-info text-center">
                        <h4 class="text-capitalize text-primary mb-1">@Html.DisplayFor(model => model.FullName)</h4>
                        @{
                            if (@User.IsInRole(GlobalVariables.CustomerRole))
                            {
                                <h5 class="text-uppercase text-danger">Customer</h5>
                            }
                            if (@User.IsInRole(GlobalVariables.ManagerRole))
                            {
                                <h5 class="text-uppercase text-danger">Manager</h5>
                            }
                            if (@User.IsInRole(GlobalVariables.AdministratorRole))
                            {
                                <h5 class="text-uppercase text-danger">Admin</h5>
                            }
                            if (@User.IsInRole(GlobalVariables.DoctorRole))
                            {
                                <h5 class="text-uppercase text-danger">Doctor</h5>
                            }
                            if (@User.IsInRole(GlobalVariables.NurseRole))
                            {
                                <h5 class="text-uppercase text-danger">Nurse</h5>
                            }
                        }
                    </div>*@
                @*</div>*@
                <div class="user-detail px-5 col-8">
                    <h5>Change password</h5>
                    <form class="row mt-4" asp-action="SubmitChangePassword">
                        <div class="form-group">
                            <input type="password" name="NewPassword" value="@ViewData["CurrentFilter"]" class="form-control" placeholder="New Password"/>
                        </div>
                        <div class="form-group">
                            <input type="password" name="ConfirmPassword" value="@ViewData["CurrentFilter"]" class="form-control" placeholder="Confirm password"/>
                        </div>
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</section>

ChildrenCare/Views/Home/Index.cshtml
@using ChildrenCare.DTOs.ServiceDTOs
@using ChildrenCare.DTOs.BlogDTOs
@model List<ChildrenCare.Entities.Slider>

@{
    ViewData["Title"] = "Home Page";
    Layout = "_Layout";
    GetFeaturedServiceListResponseDTO dto = ViewBag.Services;
    var serviceList = dto.Services.ToList();
}

<!--Header-->
<!--Home-->
<section id="home">
    <div class="welcome-wrapper d-flex justify-content-between">
        <div class="welcome-title">
            <h1>Professional Care Of Your Health.</h1>
            <p class="text-muted">There nothing more important than our good health, cause that’s our capital assest for our good future.</p>
            <div class="welcome-action">
                <a id="login" asp-controller="AppUser" asp-action="Login" class="btn btn-primary px-3">Get Started</a>
                <a asp-controller="Service" asp-action="ServiceList" class="btn btn-outline-primary px-3">Book Appointment</a>
            </div>
        </div>
        <div class="welcome-image">
            <img src="./images/doctor.png" class="w-100" alt="doctor">
        </div>
    </div>
</section>

<!--Slider-->
@{
    <section id="slider">
        <div class="container">
            <div id="carousel" class="carousel slide px-25" data-bs-ride="carousel">
                <div class="carousel-inner">
                    @{
                        int j = 0;
                    }
                    @foreach (var item in Model)
                    {
                        @if (@item.Status == 1)
                        {
                            j++;
                            var active = j == 1 ? "active" : "";
                            <a class="carousel-item @active">
                                <img src=@item.ThumbnailUrl class="d-block" style="height: 500px; width: 100%" alt=@item.Title>
                                <div class="carousel-caption d-none d-md-block">
                                    <h5>@item.Title</h5>
                                </div>
                            </a>
                        }
                    }
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carousel" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carousel" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
    </section>
}

<!--Services-->
@{
    if (serviceList != null && serviceList.Any())
    {
        <!--Services-->
        <section id="service">
            <div class="service-wrapper">
                <div class="service-title text-center">
                    <h5 class="text-primary">OUR SERVICES</h5>
                    <h1>Our Department</h1>
                    <a asp-controller="Service" asp-action="ServiceList" class="read-all float-end">View All <i class="fa-solid fa-arrow-right"></i></a>
                </div>
                <nav>
                    <div class="nav nav-tabs" id="nav-tab" role="tablist">
                        @for (var i = 0; i < serviceList.Count(); i++)
                        {
                            var tabId = "nav-" + i + "-tab";
                            var dataTarget = "#nav-" + i;
                            if (i == 0)
                            {
                                <button class="nav-link active" id="@tabId" data-bs-toggle="tab" data-bs-target="@dataTarget"
                                        type="button" role="tab" aria-controls="nav-1" aria-selected="true">
                                    @serviceList[i].Name
                                </button>
                            }
                            else
                            {
                                <button class="nav-link" id="@tabId" data-bs-toggle="tab" data-bs-target="@dataTarget"
                                        type="button" role="tab" aria-controls="nav-1" aria-selected="true">
                                    @serviceList[i].Name
                                </button>
                            }
                        }
                    </div>
                </nav>
                <div class="tab-content" id="nav-tabContent">
                    @for (var i = 0; i < serviceList.Count(); i++)
                    {
                        var tabId = "nav-" + i + "-tab";
                        var dataTarget = "nav-" + i;
                        var imageSource = string.IsNullOrWhiteSpace(serviceList[i].ThumbnailUrl) ? "https://wolper.com.au/wp-content/uploads/2017/10/image-placeholder.jpg" : serviceList[i].ThumbnailUrl;
                        var serviceName = serviceList[i].Name;
                        var serviceBriefInfo = serviceList[i].BriefInfo;
                        if (i == 0)
                        {
                            <div class="tab-pane fade show active" id="@dataTarget" role="tabpanel" aria-labelledby="@tabId">
                                <div class="service-item">
                                    <div class="service-image col-7">
                                        <img src=@imageSource alt="">
                                    </div>
                                    <div class="service-info col-5">
                                        <h4>@serviceName</h4>
                                        <p>@serviceBriefInfo</p>
                                    </div>
                                </div>
                            </div>
                        }
                        else
                        {
                            <div class="tab-pane fade show" id="@dataTarget" role="tabpanel" aria-labelledby="@tabId">
                                <div class="service-item">
                                    <div class="service-image">
                                        <img src=@imageSource alt="">
                                    </div>
                                    <div class="service-info">
                                        <h4>@serviceName</h4>
                                        <p>@serviceBriefInfo</p>
                                    </div>
                                </div>
                            </div>
                        }
                    }
                </div>
            </div>
        </section>
    }
}


<section id="hot-blog">
    <div class="hot-blog-wrapper">
        <div class="col-8 hot-blog-item-wrapper d-flex">
            @foreach (var blog in ((List<GetBlogListResponseDTO>)ViewBag.Blogs.Items).Take((2)))
            {
                {
                    <div class="col-6 hot-blog-item">
                        <a asp-controller="Blog" asp-action="BlogDetail" asp-route-id="@blog.Id">
                            <div class="hot-blog-image">
                                <img src="@blog.ThumbnailUrl" alt="@blog.Tittle">
                            </div>
                            <div class="hot-blog-info">
                                <h5>@blog.Tittle</h5>
                                <p style="text-overflow: ellipsis">@blog.BriefInfo</p>
                            </div>
                        </a>
                    </div>
                }
            }
        </div>
        <div class="col-4 ms-3 hot-blog-title">
            <h4 class="text-primary">OUR BLOGS</h4>
            <h1>Read Hotest News</h1>
            <p>
                Read the latest news and get the updates of health and treatment. You can know everthing about health
                and treatment by reading the blog.
            </p>
            <a class="read-all" asp-controller="Blog" asp-action="BlogList">Read All Blogs <i class="fa-solid fa-arrow-right"></i></a>
        </div>
    </div>
</section>